CREATE SCHEMA IF NOT EXISTS week5_raw;
CREATE SCHEMA IF NOT EXISTS week5_control;
CREATE SCHEMA IF NOT EXISTS week5_curated;

CREATE TABLE IF NOT EXISTS week5_raw.promotions_airflow (
    ingestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id TEXT NOT NULL,
    source_system TEXT NOT NULL CHECK (source_system = 'airflow'),
    promotion_id TEXT,
    product_id TEXT,
    payload JSONB NOT NULL,
    source_updated_at TIMESTAMPTZ,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payload_hash TEXT NOT NULL,
    is_valid BOOLEAN NOT NULL,
    validation_error TEXT,
    UNIQUE (source_system, promotion_id, payload_hash)
);

CREATE TABLE IF NOT EXISTS week5_raw.promotions_nifi (
    ingestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id TEXT NOT NULL,
    source_system TEXT NOT NULL CHECK (source_system = 'nifi'),
    promotion_id TEXT,
    product_id TEXT,
    payload JSONB NOT NULL,
    source_updated_at TIMESTAMPTZ,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payload_hash TEXT NOT NULL,
    is_valid BOOLEAN NOT NULL,
    validation_error TEXT,
    UNIQUE (source_system, promotion_id, payload_hash)
);

CREATE TABLE IF NOT EXISTS week5_control.pipeline_runs (
    run_id TEXT PRIMARY KEY,
    pipeline_name TEXT NOT NULL,
    source_mode TEXT NOT NULL CHECK (source_mode IN ('airflow', 'nifi')),
    batch_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN ('running', 'raw_ready', 'transforming', 'quality_failed', 'success', 'failed')
    ),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    raw_count BIGINT NOT NULL DEFAULT 0,
    accepted_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    curated_count BIGINT NOT NULL DEFAULT 0,
    error_message TEXT,
    UNIQUE (source_mode, batch_id)
);

CREATE TABLE IF NOT EXISTS week5_control.ingestion_watermarks (
    pipeline_name TEXT NOT NULL,
    source_mode TEXT NOT NULL,
    previous_watermark TIMESTAMPTZ,
    current_watermark TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (pipeline_name, source_mode)
);

CREATE TABLE IF NOT EXISTS week5_control.quality_results (
    quality_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES week5_control.pipeline_runs(run_id),
    check_name TEXT NOT NULL,
    check_status TEXT NOT NULL CHECK (check_status IN ('passed', 'failed', 'warning')),
    actual_value TEXT,
    expected_value TEXT,
    details TEXT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id, check_name)
);

CREATE TABLE IF NOT EXISTS week5_curated.sales_promotion_airflow (
    source_mode TEXT NOT NULL CHECK (source_mode = 'airflow'),
    run_id TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    item_number INTEGER NOT NULL,
    product_id TEXT NOT NULL,
    purchase_date DATE,
    promotion_id TEXT NOT NULL DEFAULT 'NO_PROMOTION',
    promotion_version INTEGER NOT NULL DEFAULT 0,
    discount_type TEXT,
    discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    item_price NUMERIC(12, 2) NOT NULL,
    freight_value NUMERIC(12, 2) NOT NULL,
    gross_amount NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL,
    net_amount_after_discount NUMERIC(12, 2) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (source_mode, order_id, item_number, promotion_id, promotion_version)
);

CREATE TABLE IF NOT EXISTS week5_curated.sales_promotion_nifi (
    source_mode TEXT NOT NULL CHECK (source_mode = 'nifi'),
    run_id TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    item_number INTEGER NOT NULL,
    product_id TEXT NOT NULL,
    purchase_date DATE,
    promotion_id TEXT NOT NULL DEFAULT 'NO_PROMOTION',
    promotion_version INTEGER NOT NULL DEFAULT 0,
    discount_type TEXT,
    discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    item_price NUMERIC(12, 2) NOT NULL,
    freight_value NUMERIC(12, 2) NOT NULL,
    gross_amount NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL,
    net_amount_after_discount NUMERIC(12, 2) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (source_mode, order_id, item_number, promotion_id, promotion_version)
);
