[pytest]
testpaths =
    exercises/week1/tests
    exercises/week2/tests
    exercises/week3/tests
    exercises/week4/tests
    exercises/week5/tests
    exercises/week6/tests
    mock_api/tests
pythonpath =
    .
    mock_api
addopts = -ra
