CREATE SCHEMA IF NOT EXISTS week6_raw;
CREATE SCHEMA IF NOT EXISTS week6_control;
CREATE SCHEMA IF NOT EXISTS week6_curated;
CREATE SCHEMA IF NOT EXISTS week6_log;

CREATE TABLE IF NOT EXISTS week6_raw.promotions (
    ingestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id TEXT NOT NULL,
    record_index INTEGER NOT NULL,
    promotion_id TEXT,
    product_id TEXT,
    payload JSONB NOT NULL,
    source_updated_at TIMESTAMPTZ,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payload_hash TEXT NOT NULL,
    is_valid BOOLEAN NOT NULL,
    validation_error TEXT,
    UNIQUE (batch_id, record_index)
);

CREATE INDEX IF NOT EXISTS idx_week6_promotions_batch
    ON week6_raw.promotions(batch_id);
CREATE INDEX IF NOT EXISTS idx_week6_promotions_latest
    ON week6_raw.promotions(promotion_id, source_updated_at DESC)
    WHERE is_valid;

CREATE TABLE IF NOT EXISTS week6_control.pipeline_runs (
    run_id TEXT PRIMARY KEY,
    pipeline_name TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    scenario TEXT NOT NULL,
    invalid_rate_threshold NUMERIC(8, 6) NOT NULL DEFAULT 0,
    status TEXT NOT NULL CHECK (
        status IN ('running', 'raw_ready', 'transforming', 'quality_failed', 'success', 'failed')
    ),
    attempt_number INTEGER NOT NULL DEFAULT 1,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    raw_count BIGINT NOT NULL DEFAULT 0,
    accepted_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    curated_count BIGINT NOT NULL DEFAULT 0,
    error_message TEXT,
    CHECK (window_end > window_start),
    CHECK (invalid_rate_threshold BETWEEN 0 AND 1)
);

CREATE INDEX IF NOT EXISTS idx_week6_pipeline_runs_latest
    ON week6_control.pipeline_runs(pipeline_name, started_at DESC);

CREATE TABLE IF NOT EXISTS week6_control.quality_results (
    quality_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES week6_control.pipeline_runs(run_id),
    check_name TEXT NOT NULL,
    check_status TEXT NOT NULL CHECK (check_status IN ('passed', 'failed', 'warning')),
    actual_value TEXT,
    expected_value TEXT,
    details TEXT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id, check_name)
);

CREATE TABLE IF NOT EXISTS week6_control.ingestion_watermarks (
    pipeline_name TEXT PRIMARY KEY,
    previous_window_end TIMESTAMPTZ,
    current_window_end TIMESTAMPTZ NOT NULL,
    run_id TEXT NOT NULL REFERENCES week6_control.pipeline_runs(run_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS week6_curated.sales_promotion (
    run_id TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    item_number INTEGER NOT NULL,
    product_id TEXT NOT NULL,
    purchase_date DATE,
    promotion_id TEXT NOT NULL DEFAULT 'NO_PROMOTION',
    promotion_version INTEGER NOT NULL DEFAULT 0,
    discount_type TEXT,
    discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    item_price NUMERIC(12, 2) NOT NULL,
    freight_value NUMERIC(12, 2) NOT NULL,
    gross_amount NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL,
    net_amount_after_discount NUMERIC(12, 2) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (order_id, item_number, promotion_id, promotion_version)
);

-- Spark chỉ ghi vào staging. Bảng snapshot công khai chỉ được thay thế sau
-- khi quality gate trên đúng run_id đạt, trong một transaction PostgreSQL.
CREATE TABLE IF NOT EXISTS week6_curated.sales_promotion_staging (
    run_id TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    item_number INTEGER NOT NULL,
    product_id TEXT NOT NULL,
    purchase_date DATE,
    promotion_id TEXT NOT NULL DEFAULT 'NO_PROMOTION',
    promotion_version INTEGER NOT NULL DEFAULT 0,
    discount_type TEXT,
    discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    item_price NUMERIC(12, 2) NOT NULL,
    freight_value NUMERIC(12, 2) NOT NULL,
    gross_amount NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL,
    net_amount_after_discount NUMERIC(12, 2) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (run_id, order_id, item_number, promotion_id, promotion_version)
);

CREATE INDEX IF NOT EXISTS idx_week6_promotion_staging_run
    ON week6_curated.sales_promotion_staging(run_id);

-- Mỗi checkpoint generation có namespace riêng. Khi xóa/tạo lại checkpoint,
-- người vận hành bắt buộc đổi stream_generation_id để epoch 0 không đè dữ liệu cũ.
CREATE TABLE IF NOT EXISTS week6_control.log_stream_generations (
    stream_generation_id TEXT PRIMARY KEY,
    query_name TEXT NOT NULL,
    checkpoint_path TEXT NOT NULL,
    last_successful_batch_id BIGINT NOT NULL DEFAULT -1,
    lineage_id TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS week6_control.log_stream_batches (
    stream_generation_id TEXT NOT NULL,
    stream_batch_id BIGINT NOT NULL,
    query_name TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    max_event_time TIMESTAMPTZ,
    raw_count BIGINT NOT NULL DEFAULT 0,
    valid_count BIGINT NOT NULL DEFAULT 0,
    invalid_count BIGINT NOT NULL DEFAULT 0,
    ingestion_lag_seconds NUMERIC(14, 3),
    status TEXT NOT NULL CHECK (status IN ('running', 'success', 'failed')),
    error_message TEXT,
    PRIMARY KEY (stream_generation_id, stream_batch_id)
);

CREATE INDEX IF NOT EXISTS idx_week6_log_stream_latest
    ON week6_control.log_stream_batches(finished_at DESC);

CREATE TABLE IF NOT EXISTS week6_log.requests_per_minute_stream_staging (
    stream_generation_id TEXT NOT NULL,
    stream_batch_id BIGINT NOT NULL,
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    request_count BIGINT NOT NULL,
    latency_sum_ms NUMERIC(20, 3) NOT NULL,
    max_latency_ms INTEGER NOT NULL,
    PRIMARY KEY (stream_generation_id, stream_batch_id, minute_start, service)
);

CREATE TABLE IF NOT EXISTS week6_log.status_distribution_stream_staging (
    stream_generation_id TEXT NOT NULL,
    stream_batch_id BIGINT NOT NULL,
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    status_code INTEGER NOT NULL CHECK (status_code BETWEEN 100 AND 599),
    request_count BIGINT NOT NULL,
    PRIMARY KEY (
        stream_generation_id, stream_batch_id, minute_start, service, status_code
    )
);

CREATE TABLE IF NOT EXISTS week6_log.requests_per_minute_stream (
    stream_generation_id TEXT NOT NULL,
    stream_batch_id BIGINT NOT NULL,
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    request_count BIGINT NOT NULL,
    latency_sum_ms NUMERIC(20, 3) NOT NULL,
    max_latency_ms INTEGER NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (stream_generation_id, stream_batch_id, minute_start, service)
);

CREATE TABLE IF NOT EXISTS week6_log.status_distribution_stream (
    stream_generation_id TEXT NOT NULL,
    stream_batch_id BIGINT NOT NULL,
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    status_code INTEGER NOT NULL CHECK (status_code BETWEEN 100 AND 599),
    request_count BIGINT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (
        stream_generation_id, stream_batch_id, minute_start, service, status_code
    )
);

-- Migration idempotent cho database đã chạy schema epoch-only trước đây.
ALTER TABLE week6_control.log_stream_batches
    ADD COLUMN IF NOT EXISTS stream_generation_id TEXT NOT NULL DEFAULT 'legacy-v1';
ALTER TABLE week6_log.requests_per_minute_stream_staging
    ADD COLUMN IF NOT EXISTS stream_generation_id TEXT NOT NULL DEFAULT 'legacy-v1';
ALTER TABLE week6_log.status_distribution_stream_staging
    ADD COLUMN IF NOT EXISTS stream_generation_id TEXT NOT NULL DEFAULT 'legacy-v1';
ALTER TABLE week6_log.requests_per_minute_stream
    ADD COLUMN IF NOT EXISTS stream_generation_id TEXT NOT NULL DEFAULT 'legacy-v1';
ALTER TABLE week6_log.status_distribution_stream
    ADD COLUMN IF NOT EXISTS stream_generation_id TEXT NOT NULL DEFAULT 'legacy-v1';
ALTER TABLE week6_control.log_stream_generations
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE week6_control.log_stream_generations
    ADD COLUMN IF NOT EXISTS lineage_id TEXT;
UPDATE week6_control.log_stream_generations
SET lineage_id=stream_generation_id
WHERE lineage_id IS NULL OR BTRIM(lineage_id)='';
ALTER TABLE week6_control.log_stream_generations
    ALTER COLUMN lineage_id SET NOT NULL;

DO $$
DECLARE
    item RECORD;
    primary_key_name TEXT;
    primary_key_definition TEXT;
BEGIN
    FOR item IN
        SELECT * FROM (VALUES
            ('week6_control', 'log_stream_batches',
             'PRIMARY KEY (stream_generation_id, stream_batch_id)',
             'stream_generation_id, stream_batch_id'),
            ('week6_log', 'requests_per_minute_stream_staging',
             'PRIMARY KEY (stream_generation_id, stream_batch_id, minute_start, service)',
             'stream_generation_id, stream_batch_id, minute_start, service'),
            ('week6_log', 'status_distribution_stream_staging',
             'PRIMARY KEY (stream_generation_id, stream_batch_id, minute_start, service, status_code)',
             'stream_generation_id, stream_batch_id, minute_start, service, status_code'),
            ('week6_log', 'requests_per_minute_stream',
             'PRIMARY KEY (stream_generation_id, stream_batch_id, minute_start, service)',
             'stream_generation_id, stream_batch_id, minute_start, service'),
            ('week6_log', 'status_distribution_stream',
             'PRIMARY KEY (stream_generation_id, stream_batch_id, minute_start, service, status_code)',
             'stream_generation_id, stream_batch_id, minute_start, service, status_code')
        ) AS definitions(schema_name, table_name, expected_definition, columns_sql)
    LOOP
        primary_key_name := NULL;
        primary_key_definition := NULL;
        SELECT constraint_name, definition
        INTO primary_key_name, primary_key_definition
        FROM (
            SELECT pk_constraint.conname AS constraint_name,
                   pg_get_constraintdef(pk_constraint.oid) AS definition
            FROM pg_constraint AS pk_constraint
            WHERE pk_constraint.conrelid = format('%I.%I', item.schema_name, item.table_name)::regclass
              AND pk_constraint.contype = 'p'
        ) AS current_primary_key;

        IF primary_key_name IS NOT NULL
           AND primary_key_definition <> item.expected_definition THEN
            EXECUTE format(
                'ALTER TABLE %I.%I DROP CONSTRAINT %I',
                item.schema_name, item.table_name, primary_key_name
            );
            primary_key_name := NULL;
        END IF;
        IF primary_key_name IS NULL THEN
            EXECUTE format(
                'ALTER TABLE %I.%I ADD PRIMARY KEY (%s)',
                item.schema_name, item.table_name, item.columns_sql
            );
        END IF;
    END LOOP;
END $$;

-- Dữ liệu epoch-only đã có được khóa vào generation migration riêng và seed
-- high-water. Checkpoint thật không thể vô tình tái dùng namespace legacy này.
INSERT INTO week6_control.log_stream_generations(
    stream_generation_id, query_name, checkpoint_path,
    last_successful_batch_id, lineage_id, is_active
)
SELECT 'legacy-v1',
       COALESCE(
           (ARRAY_AGG(query_name ORDER BY finished_at DESC NULLS LAST))[1],
           'de_genesis_week6_service_logs'
       ),
       'migration-lock://legacy-v1',
       COALESCE(
           MAX(stream_batch_id) FILTER (WHERE status='success'),
           -1
       ),
       'legacy-v1',
       FALSE
FROM week6_control.log_stream_batches
WHERE stream_generation_id='legacy-v1'
HAVING COUNT(*) > 0
ON CONFLICT (stream_generation_id) DO UPDATE
SET last_successful_batch_id=GREATEST(
        week6_control.log_stream_generations.last_successful_batch_id,
        EXCLUDED.last_successful_batch_id
    ),
    updated_at=NOW();

-- Mỗi query chỉ có một generation current. Migration chỉ dọn active trùng và
-- bootstrap generation đã từng success; generation mới chưa publish vẫn inactive.
WITH active_ranked AS (
    SELECT stream_generation_id,
           ROW_NUMBER() OVER (
               PARTITION BY query_name
               ORDER BY updated_at DESC, created_at DESC, stream_generation_id DESC
           ) AS active_rank
    FROM week6_control.log_stream_generations
    WHERE is_active
)
UPDATE week6_control.log_stream_generations AS generation
SET is_active=FALSE, updated_at=NOW()
FROM active_ranked
WHERE active_ranked.stream_generation_id=generation.stream_generation_id
  AND active_ranked.active_rank > 1;

WITH bootstrap_ranked AS (
    SELECT stream_generation_id, query_name,
           ROW_NUMBER() OVER (
               PARTITION BY query_name
               ORDER BY last_successful_batch_id DESC, updated_at DESC,
                        created_at DESC, stream_generation_id DESC
           ) AS bootstrap_rank
    FROM week6_control.log_stream_generations
    WHERE last_successful_batch_id >= 0
)
UPDATE week6_control.log_stream_generations AS generation
SET is_active=TRUE, updated_at=NOW()
FROM bootstrap_ranked
WHERE bootstrap_ranked.stream_generation_id=generation.stream_generation_id
  AND bootstrap_ranked.bootstrap_rank=1
  AND NOT EXISTS (
      SELECT 1
      FROM week6_control.log_stream_generations AS active_generation
      WHERE active_generation.query_name=bootstrap_ranked.query_name
        AND active_generation.is_active
  );

CREATE UNIQUE INDEX IF NOT EXISTS uq_week6_log_stream_active_generation
    ON week6_control.log_stream_generations(query_name)
    WHERE is_active;

CREATE OR REPLACE VIEW week6_log.live_requests_per_minute AS
SELECT minute_start,
       service,
       SUM(request_count)::BIGINT AS request_count,
       ROUND(SUM(latency_sum_ms) / NULLIF(SUM(request_count), 0), 3) AS avg_latency_ms,
       MAX(max_latency_ms) AS max_latency_ms
FROM week6_log.requests_per_minute_stream AS report
JOIN week6_control.log_stream_generations AS generation
  ON generation.stream_generation_id=report.stream_generation_id
JOIN week6_control.log_stream_generations AS active_generation
  ON active_generation.query_name=generation.query_name
 AND active_generation.lineage_id=generation.lineage_id
 AND active_generation.is_active
GROUP BY minute_start, service;

CREATE OR REPLACE VIEW week6_log.live_status_distribution AS
WITH counts AS (
    SELECT minute_start,
           service,
           status_code,
           SUM(request_count)::BIGINT AS request_count
    FROM week6_log.status_distribution_stream AS report
    JOIN week6_control.log_stream_generations AS generation
      ON generation.stream_generation_id=report.stream_generation_id
    JOIN week6_control.log_stream_generations AS active_generation
      ON active_generation.query_name=generation.query_name
     AND active_generation.lineage_id=generation.lineage_id
     AND active_generation.is_active
    GROUP BY minute_start, service, status_code
)
SELECT minute_start,
       service,
       status_code,
       request_count,
       ROUND(
           request_count * 100.0
           / NULLIF(SUM(request_count) OVER (PARTITION BY minute_start, service), 0),
           3
       ) AS percentage
FROM counts;

-- Airflow dùng các bảng dưới đây cho report cửa sổ đóng và backfill. Dữ liệu
-- staging được DQ trước rồi mới publish nguyên tử vào hai bảng canonical.
CREATE TABLE IF NOT EXISTS week6_control.log_report_runs (
    run_id TEXT PRIMARY KEY,
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('scheduled', 'backfill')),
    settlement_seconds INTEGER NOT NULL DEFAULT 180,
    data_available_through TIMESTAMPTZ,
    hdfs_staging_path TEXT,
    hdfs_published_path TEXT,
    status TEXT NOT NULL CHECK (
        status IN ('running', 'transforming', 'quality_failed', 'success', 'failed')
    ),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    source_count BIGINT NOT NULL DEFAULT 0,
    minute_report_count BIGINT NOT NULL DEFAULT 0,
    status_report_count BIGINT NOT NULL DEFAULT 0,
    error_message TEXT,
    CHECK (window_end > window_start)
);

ALTER TABLE week6_control.log_report_runs
    ADD COLUMN IF NOT EXISTS settlement_seconds INTEGER NOT NULL DEFAULT 180;
ALTER TABLE week6_control.log_report_runs
    ADD COLUMN IF NOT EXISTS data_available_through TIMESTAMPTZ;
ALTER TABLE week6_control.log_report_runs
    ADD COLUMN IF NOT EXISTS hdfs_staging_path TEXT;
ALTER TABLE week6_control.log_report_runs
    ADD COLUMN IF NOT EXISTS hdfs_published_path TEXT;

CREATE INDEX IF NOT EXISTS idx_week6_log_report_runs_latest
    ON week6_control.log_report_runs(started_at DESC);

CREATE TABLE IF NOT EXISTS week6_control.log_quality_results (
    run_id TEXT NOT NULL REFERENCES week6_control.log_report_runs(run_id),
    check_name TEXT NOT NULL,
    check_status TEXT NOT NULL CHECK (check_status IN ('passed', 'failed')),
    actual_value TEXT,
    expected_value TEXT,
    details TEXT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (run_id, check_name)
);

CREATE TABLE IF NOT EXISTS week6_control.log_report_watermark (
    pipeline_name TEXT PRIMARY KEY,
    current_window_end TIMESTAMPTZ NOT NULL,
    run_id TEXT NOT NULL REFERENCES week6_control.log_report_runs(run_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS week6_log.requests_per_minute_staging (
    run_id TEXT NOT NULL,
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    request_count BIGINT NOT NULL,
    avg_latency_ms NUMERIC(14, 3) NOT NULL,
    max_latency_ms INTEGER NOT NULL,
    PRIMARY KEY (run_id, minute_start, service)
);

CREATE TABLE IF NOT EXISTS week6_log.status_distribution_staging (
    run_id TEXT NOT NULL,
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    status_code INTEGER NOT NULL CHECK (status_code BETWEEN 100 AND 599),
    request_count BIGINT NOT NULL,
    percentage NUMERIC(8, 3) NOT NULL CHECK (percentage BETWEEN 0 AND 100),
    PRIMARY KEY (run_id, minute_start, service, status_code)
);

CREATE TABLE IF NOT EXISTS week6_log.requests_per_minute (
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    request_count BIGINT NOT NULL,
    avg_latency_ms NUMERIC(14, 3) NOT NULL,
    max_latency_ms INTEGER NOT NULL,
    run_id TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (minute_start, service)
);

CREATE TABLE IF NOT EXISTS week6_log.status_distribution (
    minute_start TIMESTAMPTZ NOT NULL,
    service TEXT NOT NULL,
    status_code INTEGER NOT NULL CHECK (status_code BETWEEN 100 AND 599),
    request_count BIGINT NOT NULL,
    percentage NUMERIC(8, 3) NOT NULL CHECK (percentage BETWEEN 0 AND 100),
    run_id TEXT NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (minute_start, service, status_code)
);
