CREATE SCHEMA IF NOT EXISTS week6_raw;
CREATE SCHEMA IF NOT EXISTS week6_control;
CREATE SCHEMA IF NOT EXISTS week6_curated;

CREATE TABLE IF NOT EXISTS week6_raw.promotions (
    ingestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id TEXT NOT NULL,
    record_index INTEGER NOT NULL,
    promotion_id TEXT,
    product_id TEXT,
    payload JSONB NOT NULL,
    source_updated_at TIMESTAMPTZ,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payload_hash TEXT NOT NULL,
    is_valid BOOLEAN NOT NULL,
    validation_error TEXT,
    UNIQUE (batch_id, record_index)
);

CREATE INDEX IF NOT EXISTS idx_week6_promotions_batch
    ON week6_raw.promotions(batch_id);
CREATE INDEX IF NOT EXISTS idx_week6_promotions_latest
    ON week6_raw.promotions(promotion_id, source_updated_at DESC)
    WHERE is_valid;

CREATE TABLE IF NOT EXISTS week6_control.pipeline_runs (
    run_id TEXT PRIMARY KEY,
    pipeline_name TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    scenario TEXT NOT NULL,
    invalid_rate_threshold NUMERIC(8, 6) NOT NULL DEFAULT 0,
    status TEXT NOT NULL CHECK (
        status IN ('running', 'raw_ready', 'transforming', 'quality_failed', 'success', 'failed')
    ),
    attempt_number INTEGER NOT NULL DEFAULT 1,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at TIMESTAMPTZ,
    raw_count BIGINT NOT NULL DEFAULT 0,
    accepted_count BIGINT NOT NULL DEFAULT 0,
    rejected_count BIGINT NOT NULL DEFAULT 0,
    curated_count BIGINT NOT NULL DEFAULT 0,
    error_message TEXT,
    CHECK (window_end > window_start),
    CHECK (invalid_rate_threshold BETWEEN 0 AND 1)
);

CREATE INDEX IF NOT EXISTS idx_week6_pipeline_runs_latest
    ON week6_control.pipeline_runs(pipeline_name, started_at DESC);

CREATE TABLE IF NOT EXISTS week6_control.quality_results (
    quality_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES week6_control.pipeline_runs(run_id),
    check_name TEXT NOT NULL,
    check_status TEXT NOT NULL CHECK (check_status IN ('passed', 'failed', 'warning')),
    actual_value TEXT,
    expected_value TEXT,
    details TEXT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (run_id, check_name)
);

CREATE TABLE IF NOT EXISTS week6_control.ingestion_watermarks (
    pipeline_name TEXT PRIMARY KEY,
    previous_window_end TIMESTAMPTZ,
    current_window_end TIMESTAMPTZ NOT NULL,
    run_id TEXT NOT NULL REFERENCES week6_control.pipeline_runs(run_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS week6_curated.sales_promotion (
    run_id TEXT NOT NULL,
    batch_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    item_number INTEGER NOT NULL,
    product_id TEXT NOT NULL,
    purchase_date DATE,
    promotion_id TEXT NOT NULL DEFAULT 'NO_PROMOTION',
    promotion_version INTEGER NOT NULL DEFAULT 0,
    discount_type TEXT,
    discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    item_price NUMERIC(12, 2) NOT NULL,
    freight_value NUMERIC(12, 2) NOT NULL,
    gross_amount NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL,
    net_amount_after_discount NUMERIC(12, 2) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (order_id, item_number, promotion_id, promotion_version)
);
